server:
  port: 8761


eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false
    #\u901A\u8FC7eureka.client.registerWithEureka\uFF1Afalse\u548CfetchRegistry\uFF1Afalse\u6765\u8868\u660E\u81EA\u5DF1\u662F\u4E00\u4E2Aeureka server
    service-url:
      default-zone: http://${eureka.instance.hostname}:${server.port}/eureka-server

spring:
  application:
    name: eureka-server