eureka:
  client:
    service-url:
      defaultZone: http://root:123456@peer1.com:7901/eureka/

server:
  port: 8096

spring:
  application:
    name: eureka-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      routes:
        - id: service-hi
          uri: lb://EUREKA-CLIENT
          predicates:
            - Path=/demo/**
          filters:
            - StripPrefix=1

